export const settingsConfig = [
    {
      id: 1, 
      key: "autoConsumption",
      label: "Want auto consumption for Inventory?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 2,
      key: "mappedRestaurants",
      label: "Mapped Restaurants/Kitchens/Stores",
      type: "multi-select",
      options: [
        { value: "demoHO", label: "Petpooja Tutorials Demo HO" },
        { value: "demoKitchen", label: "Petpooja Tutorials Demo Central Kitchen" },
      ],
      defaultValue: [],
      note: "Note: For all restaurants, please make it empty.",
    },
    {
      id: 3,
      key: "notifyOnStockLevel",
      label: "Get Notification when item reaches at par stock level?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 4,
      key: "outOfStockStatus",
      label: "Send Notification to kitchen when item reaches at par stock level?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 5,
      key: "shipToBill",
      label: "Put item as out of stock status when item puantity get below minimum stock level?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 6,
      key: "roundOffInvoice",
      label: "Allow the user to raise a request for purchase when the stock at the kitchen/restaurant level is negative?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 7,
      key: "revertConsumption",
      label: "Want Ship to bill to configuration ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 8,
      key: "displayAveragePurchase",
      label: "Want to set invoice total amount in round figure/round off ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 9,
      key: "salesInvoiceLabel",
      label: "Sales Invoice Label",
      type: "text",
      placeholder: "Enter label (e.g., TAX INVOICE)",
      defaultValue: "TAX INVOICE",
    },
  
    {
      id: 10,
      key: "getNotifications",
      label: "Revert consumption due to cancellation of an online order ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 11,
      key: "raisePurchaseRequest",
      label: "want to display average purchase(Without tax) price as internal transfer/sale/sale return price ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: true,
    },
  
    {
      id: 12,
      key: "averagePurchaseDays",
      label: "Choose how many days you want to use to obtain the latest average purchase price.",
      type: "radio",
      options: ["15", "30", "45", "90"],
      defaultValue: "15",
    },
    {
      id: 13,
      key: "perchaseItem",
      label: "perchase invoice Label",
      type: "text",
      defaultValue: "Invoice",
    },
    {
      id: 14,
      key: "transferSale",
      label: "Allow the user to raise a internal transfer/sale when the stock at the kitchen/restaurant level is negative ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 15,
      key: "taxPerchase",
      label: "Want to display Tax in purchase order ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 16,
      key: "editDeletePurchase",
      label: "Allow edit/delete of purchase once entries are done?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 17,
      key: "IncompletePurchaseOrder",
      label: "Allow for incompalete purchase order?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 18,
      key: "AddWastageStock",
      label: "Want to allow for add Wastage stock for previous date?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 19,
      key: "usetCanNotThePrice",
      label: "Do you wnat to lock prices in purchase and consumption modules ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 20,
      key: "displayCurrentStockInPurchase",
      label: "Do you want to display current stock in purchase and consumption modules ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 21,
      key: "addInternalTransfer/Sale",
      label: "Want to allow for add internal Transfer/Sale for previous date ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 22,
      key: "PreviousDateAddPurchase",
      label: "Want to allow for add purchase for previous date?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 23,
      key: "beingApproved",
      label: "Do you want to add purchase from a PO without it being approved by the restarant/kitchen in their internal transfer module ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 24,
      key: "AdvanshPrice",
      label: "Want to allow for generate proforma in sale",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 25,
      key: "averagePurchaseRice",
      label: "Want to capture average purchase rice for converted products based in row materials use in conversion",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 26,
      key: "purchase&SalesReturns",
      label: "Enable pre-configured reasons at an item level to be in place for description while creating purchase & sales returns",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 27,
      key: "creatingWastage",
      label: "Enable Pre-configured reasons at an item level to be in place for description while Creating wastage.",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 28,
      key: "outetType ",
      label: "Outet type (Ownership)",
      type: "multi-select",
      options: [
        { value: "demoHO", label: "Petpooja Tutorials Demo HO" },
        { value: "demoKitchen", label: "Petpooja Tutorials Demo Central Kitchen" },
      ],
      defaultValue: [],
    },
    {
      id: 29,
      key: "barcodeShow",
      label: "Want to use barcode in sales/transtfer/purchase ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 30,
      key: "RestrictConversion",
      label: "Restrict conversion even if the stock of the raw material used in conversion would become negative ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
    {
      id: 31,
      key: "deliverTo ",
      label: "In add request for purchase 'Deliver To'",
      type: "multi-select",
      options: [
        { value: "demoHO", label: "Petpooja Tutorials Demo HO" },
        { value: "demoKitchen", label: "Petpooja Tutorials Demo Central Kitchen" },
      ],
      defaultValue: [],
    },
    {
      id: 32,
      key: "RestrictOutlet",
      label: "Restrict outlet to raise a purchase order below MoQ ?",
      type: "radio",
      options: ["Yes", "No"],
      defaultValue: false,
    },
  ];
  